"""
Auto-generated self-healing test
Generated by: HealerAgent (Part 5 - AutoGen)
Anomaly: EMPTY_SUCCESS_RESPONSE
Fix pattern: INC-019 - Add response body assertion to catch empty 200 responses
Round: 2
"""

import pytest


def test_healed_empty_success_response_api_auth_refresh_round2():
    """
    Self-healing test for: EMPTY_SUCCESS_RESPONSE
    Affected: ['/api/auth/refresh', '/api/recommendations']
    Fix: Add response body assertion to catch empty 200 responses
    """
    # Simulated response for testing the fix pattern
    class MockResponse:
        status_code = 200
        content = b""  # Empty body - this should fail

    response = MockResponse()
    url = "/api/auth/refresh"

    # Fix assertion - will catch empty responses
    assert response.status_code == 200
    assert len(response.content) > 0, (
        "Empty response body on " + url + " - silent failure detected"
    )
